<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dx_psw_products"
 *
 * Auto generated by Extension Builder 2018-03-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PSW-Angebote',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Richard Braun',
    'author_email' => 'braun@digiturax.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
