version: "3.9"

services: 
  docasys-app:
    container_name: docasys-app
    build: 
      context: ./app
    restart: always
    volumes:
      - ./app/typo3:/var/www/html
      - ./app/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 80:80

  docasys-db:
    container_name: docasys-db
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/run:/var/run/mysqld
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cs-326244_doca"
      MYSQL_USER: "cs-32_doca_u"
      MYSQL_PASSWORD: "cs-32_doca_u"
    ports:
      - 3306:3306

  docasys-db-admin:
    container_name: docasys-db-admin
    image: phpmyadmin:5.1.3
    restart: always
    environment: 
      PMA_HOST: "docasys-db"
    ports:
      - 8080:80
