<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dx_upload_notification"
 *
 * Auto generated by Extension Builder 2017-10-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Upload Notification',
    'description' => 'Backend-Modul, um Frontend-Nutzer zu informieren, wenn auf einer Seite neue Dateien hochgeladen wurden.',
    'category' => 'be',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
