<?php
    /***************************************************************
    * Extension Manager/Repository config file for ext: "wise_docasys_backend"
    *
    * Auto generated by Extension Builder 2018-03-21
    *
    * Manual updates:
    * Only the data in the array - anything else is removed by next write.
    * "version" and "dependencies" must not be touched!
    ***************************************************************/
    $EM_CONF[$_EXTKEY ] = [
        'title' => 'DOCASYS Backend',
        'description' => '',
        'category' => 'module',
        'author' => 'Dr. Richard Braun',
        'author_email' => 'richard.braun@tu-dresden.de',
        'state' => 'stable',
        'internal' => '',
        'uploadfolder' => 1,
        'clearCacheOnLoad' => 0,
        'version' => '1.1.1',
        'constraints' => [
            'depends' => [
                'typo3' => '7.6.0-7.6.99',
                // 'wise_docasys_domain_designer' => '1.0.0-9.9.99'
            ],
            'conflicts' => [],
            'suggests' => [],
        ],
    ];
