<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wise_docasys_bpmn_modeler"
 *
 * Auto generated by Extension Builder 2018-03-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BPMN Modeler',
    'description' => '',
    'category' => 'module',
    'author' => 'Dr. Richard Braun',
    'author_email' => 'richard.braun@tu-dresden.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
